src/Bundle/RuntimeConfigBundle/Entity/Parameter.php
<?php

/**
 * Zym Framework
 *
 * This file is part of the Zym package.
 *
 * @link      https://github.com/geoffreytran/zym for the canonical source repository
 * @copyright Copyright (c) 2014 Geoffrey Tran <geoffrey.tran@gmail.com>
 * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3 License
 */

namespace Zym\Bundle\RuntimeConfigBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use OpenSky\Bundle\RuntimeConfigBundle\Model\Parameter as BaseParameter;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Acl\Model\DomainObjectInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="Zym\Bundle\RuntimeConfigBundle\Repository\ParameterRepository")
 * @ORM\Table(name="parameters")
 * @UniqueEntity(groups={"Entity"}, fields={"name"}, message="A parameter with the same name already exists; name must be unique")
 */
class Parameter extends BaseParameter implements DomainObjectInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string")
     * @Assert\Length(groups={"Entity"}, min="0", max="255")
     * @Assert\NotBlank(groups={"Entity"})
     */
    protected $name;

    /**
     * @ORM\Column(type="json", nullable=true)
     * @Assert\Length(groups={"Entity"}, min="0", max="255")
     */
    protected $value = [];

    /**
     * {@inheritdoc}
     */
    public function getObjectIdentifier()
    {
        return md5($this->getName());
    }
}

src/Bundle/RuntimeConfigBundle/Form/ParameterType.php
<?php

/**
 * Zym Framework
 *
 * This file is part of the Zym package.
 *
 * @link      https://github.com/geoffreytran/zym for the canonical source repository
 * @copyright Copyright (c) 2014 Geoffrey Tran <geoffrey.tran@gmail.com>
 * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3 License
 */

namespace Zym\Bundle\RuntimeConfigBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class ParameterType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('value', ParameterValueType::class)
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return '';
    }
}

src/Bundle/RuntimeConfigBundle/Controller/ParametersController.php
<?php

/**
 * Zym Framework
 *
 * This file is part of the Zym package.
 *
 * @link      https://github.com/geoffreytran/zym for the canonical source repository
 * @copyright Copyright (c) 2014 Geoffrey Tran <geoffrey.tran@gmail.com>
 * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3 License
  */

namespace Zym\Bundle\RuntimeConfigBundle\Controller;

use JMS\SecurityExtraBundle\Annotation\SecureParam;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Acl\Domain\ObjectIdentity;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Translation\TranslatorInterface;
use Zym\Bundle\RuntimeConfigBundle\Entity\Parameter;
use Zym\Bundle\RuntimeConfigBundle\Form\DeleteType;
use Zym\Bundle\RuntimeConfigBundle\Form\ParameterType;
use Zym\Bundle\RuntimeConfigBundle\Manager\ParameterManager;

/**
 * Runtime Config Controller
 *
 * @author    Geoffrey Tran
 * @copyright Copyright (c) 2011 Zym. (http://www.zym.com/)
 */
class ParametersController extends Controller
{
    /**
     * @var AuthorizationCheckerInterface
     */
    private $authorizationChecker;

    /**
     * @var FormFactoryInterface
     */
    private $formFactory;

    /**
     * @var ParameterManager
     */
    private $parameterManager;

    /**
     * @var TranslatorInterface
     */
    private $translator;

    public function __construct(
        AuthorizationCheckerInterface $authorizationChecker,
        FormFactoryInterface $formFactory,
        ParameterManager $parameterManager,
        TranslatorInterface $translator
    ) {
        $this->authorizationChecker = $authorizationChecker;
        $this->formFactory = $formFactory;
        $this->parameterManager = $parameterManager;
        $this->translator = $translator;
    }

    /**
     * @Route("/", name="zym_runtime_config_parameters")
     * @Template()
     *
     * @param Request $request
     * @return array
     */
    public function listAction(Request $request)
    {
        $page     = $request->query->get('page', 1);
        $limit    = $request->query->get('limit', 50);
        $orderBy  = $request->query->get('orderBy');
        $filterBy = $request->query->get('filterBy');

        $parameters = $this->parameterManager->findParameters($filterBy, $page, $limit, $orderBy);

        return [
            'parameters' => $parameters,
        ];
    }

    /**
     * Show a parameter
     *
     * @Route(
     *     "/{name}/view.{_format}",
     *     name="zym_runtime_config_parameters_show",
     *     defaults = {
     *         "_format" = "html"
     *     },
     *     requirements = {
     *         "id" = "\d+",
     *         "_format" = "html|json"
     *     }
     * )
     * @ParamConverter("parameter", class="ZymRuntimeConfigBundle:Parameter")
     * @Template()
     *
     * @SecureParam(name="parameter", permissions="VIEW")
     *
     * @param Parameter $parameter
     * @return array
     */
    public function showAction(Parameter $parameter)
    {
        return [
            'parameter' => $parameter,
        ];
    }

    /**
     * @Route(
     *     "/add.{_format}",
     *     name="zym_runtime_config_parameters_add",
     *     defaults={
     *         "_format" = "html"
     *     }
     * )
     * @Template()
     *
     * @param Request $request
     * @return array|RedirectResponse
     */
    public function addAction(Request $request)
    {
        if (!$this->authorizationChecker->isGranted('CREATE', new ObjectIdentity('class', Parameter::class))) {
            throw new AccessDeniedException();
        }

        $parameter = new Parameter();

        $form = $this->formFactory->create(ParameterType::class, $parameter);

        if ($request->isMethod(Request::METHOD_POST)) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $this->parameterManager->createParameter($parameter);

                $this->addFlash('success', $this->translator->trans('Added successfully!'));

                return $this->redirectToRoute('zym_runtime_config_parameters');
            }
        }

        return [
            'form' => $form->createView(),
        ];
    }

    /**
     * @Route("/{name}/edit", name="zym_runtime_config_parameters_edit")
     * @ParamConverter("parameter", class="ZymRuntimeConfigBundle:Parameter")
     * @Template()
     *
     * @SecureParam(name="parameter", permissions="EDIT")
     *
     * @param Request $request
     * @param Parameter $parameter
     * @return array|RedirectResponse
     */
    public function editAction(Request $request, Parameter $parameter)
    {
        $origParameter = clone $parameter;
        $form = $this->formFactory->create(ParameterType::class, $parameter);

        if ($request->isMethod(Request::METHOD_POST)) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $this->parameterManager->saveParameter($parameter);

                $this->addFlash('success', $this->translator->trans('Changes saved!'));

                return $this->redirectToRoute('zym_runtime_config_parameters');
            }
        }

        return [
            'parameter' => $origParameter,
            'form' => $form->createView(),
        ];
    }

    /**
     * Delete a parameter
     *
     * @param Parameter $parameter
     *
     * @Route(
     *     "/{name}",
     *     requirements={},
     *     methods={"DELETE"}
     * )
     * @Route(
     *     "/{name}/delete.{_format}",
     *     name="zym_runtime_config_parameters_delete",
     *     defaults = {
     *         "_format" = "html"
     *     },
     *     requirements = {
     *         "_format" = "html|json|ajax"
     *     }
     * )
     *
     * @Template()
     *
     * @SecureParam(name="parameter", permissions="DELETE")
     *
     * @param Request $request
     * @param Parameter $parameter
     * @return array|RedirectResponse
     */
    public function deleteAction(Request $request, Parameter $parameter)
    {
        $origParameter = clone $parameter;

        $form = $this->formFactory->create(DeleteType::class, $parameter);

        if ($request->isMethod(Request::METHOD_POST)) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $this->parameterManager->deleteParameter($parameter);

                $this->addFlash('success', $this->translator->trans('Parameter Deleted'));

                return $this->redirectToRoute('zym_runtime_config_parameters');
            }
        }

        if ($request->isMethod(Request::METHOD_DELETE)) {
            $this->parameterManager->deleteParameter($parameter);

            return $this->redirectToRoute('zym_runtime_config_parameters');
        }

        return [
            'parameter' => $origParameter,
            'form' => $form->createView(),
        ];
    }
}

src/Bundle/RuntimeConfigBundle/Resources/views/Parameters/add.html.twig
{% extends 'ZymRuntimeConfigBundle::layout.html.twig' %}

{% block title %}{{ 'Add a Parameter' | trans({}, 'ZymRuntimeConfigBundle') }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>
            {{ 'New Parameter' | trans({}, 'ZymRuntimeConfigBundle') }}
            <small>{{ 'Create a new parameter' | trans({}, 'ZymRuntimeConfigBundle') }}</small>
        </h1>
    </div>

    <p>
        {% trans from 'ZymRuntimeConfigBundle' %}Parameters allow for advanced custom configurations. Only modify parameters if you know what you are doing.{% endtrans %}
    </p>

    {{ form_start(form, { 'action': path('zym_runtime_config_parameters_add'), 'attr': { 'class': 'form-horizontal' } }) }}
        {{ form_rest(form) }}
        <fieldset class="form-actions">
            <button type="submit" class="btn btn-primary">{{ 'Create' | trans({}, 'ZymRuntimeConfigBundle') }}</button>
            <button type="button" class="btn" onclick="history.back();">{{ 'Cancel' | trans({}, 'ZymRuntimeConfigBundle') }}</button>
        </fieldset>
    {{ form_end(form) }}
{% endblock %}

src/Bundle/RuntimeConfigBundle/Resources/views/Parameters/delete.ajax.twig
<div class="modal-header">
    <a href="#" class="close" data-dismiss="modal">&times;</a>
    <h3>{{ 'Confirm Deletion' | trans({}, 'ZymRuntimeConfigBundle') }}</h3>
</div>

<div class="modal-body">
    <p>
        You are about to delete parameter <strong>"{{ parameter.name |e }}"</strong>.
        This action cannot be undone.<br />
        <strong>Are you sure you want to proceed?</strong>
    </p>
</div>

<div class="modal-footer">
    {{ form_start(form, { 'action': path('zym_runtime_config_parameters_delete', { 'name': parameter.name }) }) }}
        {{ form_rest(form) }}
        <input class="btn btn-danger" type="submit" value="{{ 'Confirm Deletion' | trans({}, 'ZymRuntimeConfigBundle') }}" />
        <a href="#" class="btn" data-dismiss="modal">{{ 'Cancel' | trans({}, 'ZymRuntimeConfigBundle') }}</a>
    {{ form_end(form) }}
</div>

src/Bundle/RuntimeConfigBundle/Resources/views/Parameters/delete.html.twig
{% extends 'ZymRuntimeConfigBundle::layout.html.twig' %}

{% block title %}{{ 'Delete Parameter' | trans({}, 'ZymRuntimeConfigBundle') }}{% endblock %}

{% block content %}
    <h3>{{ 'Confirm Deletion' | trans({}, 'ZymRuntimeConfigBundle') }}</h3>

    <p>
        You are about to delete parameter <strong>"{{ parameter.name |e }}"</strong>.
        This action cannot be undone.<br />
        <strong>Are you sure you want to proceed?</strong>
    </p>

    {{ form_start(form, { 'action': path('zym_runtime_config_parameters_delete', 'name': parameter.name) }) }}
        {{ form_rest(form) }}
        <fieldset class="form-actions">
            <button class="btn btn-danger" type="submit">{{ 'Confirm Deletion' | trans({}, 'ZymRuntimeConfigBundle') }}</button>
            <button type="button" class="btn" onclick="history.back();">{{ 'Cancel' | trans({}, 'ZymRuntimeConfigBundle') }}</button>
        </fieldset>
    {{ form_end(form) }}
{% endblock %}

src/Bundle/RuntimeConfigBundle/Resources/views/Parameters/edit.html.twig
{% extends 'ZymRuntimeConfigBundle::layout.html.twig' %}

{% block title %}{{ 'Edit Parameter' | trans({}, 'ZymRuntimeConfigBundle') }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>
            {{ 'Edit Parameter' | trans({}, 'ZymRuntimeConfigBundle') |e }}
            <small>{{ parameter.name | trans({}, 'ZymRuntimeConfigBundle') |e }}</small>
        </h1>
    </div>

    <div class="btn-toolbar">
        <div class="btn-group">
            <a class="btn" href="javascript: history.back();">
                <i class="icon-arrow-left"></i>
                {{ 'Back' | trans({}, 'ZymRuntimeConfigBundle') }}
            </a>
        </div>

        <div class="btn-group">
            <a class="btn" href="{{ path('zym_security_acl_object_aces', { 'type': 'Zym\\Bundle\\RuntimeConfigBundle\\Entity\\Parameter', 'identifier': parameter.objectIdentifier }) }}">
                <i class="icon-lock"></i>
                {{ 'Permissions' | trans({}, 'ZymRuntimeConfigBundle') }}
            </a>
        </div>
    </div>

    {{ form_start(form, { 'action': path('zym_runtime_config_parameters_edit', 'name': parameter.name), 'attr': { 'class': 'form-horizontal' } }) }}
        {{ form_rest(form) }}
        <fieldset class="form-actions">
            <button type="submit" class="btn btn-primary">{{ 'Save changes' | trans({}, 'ZymRuntimeConfigBundle') }}</button>
            <button type="button" class="btn" onclick="history.back();">{{ 'Cancel' | trans({}, 'ZymRuntimeConfigBundle') }}</button>
        </fieldset>
    {{ form_end(form) }}
{% endblock %}

src/Bundle/RuntimeConfigBundle/Resources/views/Parameters/list.html.twig
{% extends 'ZymRuntimeConfigBundle::layout.html.twig' %}

{% block title %}{{ 'Parameters' | trans({}, 'ZymRuntimeConfigBundle') }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1 class="pull-left">
            {{ 'Parameters' | trans({}, 'ZymRuntimeConfigBundle') }}
            <small>{{ 'Manage parameters' | trans({}, 'ZymRuntimeConfigBundle') }}</small>
        </h1>

        <div class="clearfix" style="clear:both"></div>
    </div>

    <div class="btn-toolbar">
        <div class="btn-group">
            {% if is_granted('CREATE', ['class', 'Zym\\Bundle\\RuntimeConfigBundle\\Entity\\Parameter']) %}
            <a class="btn" href="{{ path('zym_runtime_config_parameters_add') }}">
                <i class="icon-plus"></i>
                {{ 'New Parameter' | trans({}, 'ZymRuntimeConfigBundle') }}
            </a>
            {% endif %}
        </div>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>{{ 'Actions' | trans({}, 'ZymRuntimeConfigBundle') }}</th>
            </tr>
        </thead>

        <tbody>
        {% for parameter in parameters %}
            {% if is_granted('VIEW', parameter) %}
            <tr>
                <td>
                    <a href="{{ path('zym_runtime_config_parameters_show', { 'name': parameter.name, '_format': 'html' }) }}">{{ parameter.name |e }}</a>
                    <div class="description">{{ parameter.value | json_encode |e }}</div>
                </td>
                <td>
                    <div class="btn-group" style="width: 300px">
                        <a class="btn" href="{{ path('zym_runtime_config_parameters_show', { 'name': parameter.name, '_format': 'html' }) }}">
                            <i class="icon-share"></i>
                            {{ 'View' | trans({}, 'ZymRuntimeConfigBundle') }}
                        </a>

                        {% if is_granted('EDIT', parameter) %}
                        <a class="btn" href="{{ path('zym_runtime_config_parameters_edit', { 'name': parameter.name }) }}">
                            <i class="icon-edit"></i>
                            {{ 'Edit' | trans({}, 'ZymRuntimeConfigBundle') }}
                        </a>
                        {% endif %}

                        {% if is_granted('DELETE', parameter) %}
                        <a class="btn" href="{{ path('zym_runtime_config_parameters_delete', { 'name': parameter.name }) }}" data-toggle="ajax-modal">
                            <i class="icon-remove"></i>
                            {{ 'Delete' | trans({}, 'ZymRuntimeConfigBundle') }}
                        </a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

    {% if parameters | length <= 0 %}
        <p>
            {{ 'No parameters added yet.' | trans({}, 'ZymRuntimeConfigBundle') }}

            {% if is_granted('CREATE', ['class', 'Zym\\Bundle\\RuntimeConfigBundle\\Entity\\Parameter']) %}
            <a class="" href="{{ path('zym_runtime_config_parameters_add') }}">{{ 'Create a parameter.' | trans({}, 'ZymRuntimeConfigBundle') }}</a>
            {% endif %}
        </p>
    {% endif %}

    {{ knp_pagination_render(parameters) }}
{% endblock %}

src/Bundle/RuntimeConfigBundle/Resources/views/Parameters/list.json.twig
{% spaceless %}

{% set menusData = {} %}

{% for menu in menus %}
    {%
        set menusData = menusData | merge({
            "menus": [{
                "id": menu.name,
                "name": menu.label,
                "description": menu.description,
                "options": menu.options
            }]
        })
    %}
{% endfor %}

{{ menusData | json_encode | raw }}
{% endspaceless %}

src/Bundle/RuntimeConfigBundle/Resources/views/Parameters/show.html.twig
{% extends 'ZymRuntimeConfigBundle::layout.html.twig' %}

{% block title %}{{ 'Viewing Parameter' | trans({}, 'ZymRuntimeConfigBundle') }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>
            {{ 'Viewing Parameter' | trans({}, 'ZymRuntimeConfigBundle') |e }}
            <small>{{ parameter.name | trans({}, 'ZymRuntimeConfigBundle') |e }}</small>
        </h1>
    </div>

    <div class="btn-toolbar">
        <div class="btn-group">
            <a class="btn" href="javascript: history.back();">
                <i class="icon-arrow-left"></i>
                {{ 'Back' | trans({}, 'ZymRuntimeConfigBundle') }}
            </a>
        </div>

        <div class="btn-group">
            {% if is_granted('EDIT', parameter) %}
            <a class="btn" href="{{ path('zym_runtime_config_parameters_edit', { 'name': parameter.name }) }}">
                <i class="icon-edit"></i>
                {{ 'Edit' | trans({}, 'ZymRuntimeConfigBundle') }}
            </a>
            {% endif %}

            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="caret"></span>
            </a>

            <ul class="dropdown-menu">
                {% if is_granted('DELETE', parameter) %}
                <li>
                    <a href="{{ path('zym_runtime_config_parameters_delete', { 'name': parameter.name }) }}" data-toggle="ajax-modal">
                        <i class="icon-remove"></i>
                        {{ 'Delete' | trans({}, 'ZymRuntimeConfigBundle') }}
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>

        <div class="btn-group">
            <a class="btn" href="{{ path('zym_security_acl_object_aces', { 'type': 'Zym\\Bundle\\RuntimeConfigBundle\\Entity\\Parameter', 'identifier': parameter.objectIdentifier }) }}">
                <i class="icon-lock"></i>
                {{ 'Permissions' | trans({}, 'ZymRuntimeConfigBundle') }}
            </a>
        </div>
    </div>

    <h2>JSON Data</h2>
    <pre>
        {{- parameter.value | json_encode |e -}}
    </pre>

    <h2>Interpreted</h2>
    {% debug parameter.value %}
{% endblock %}

src/Bundle/RuntimeConfigBundle/Resources/views/Parameters/show.json.twig
{%
set menuData = {
    "id": menu.id,
    "name": menu.name,
    "label": menu.label,
    "description": menu.description,
    "options": menu.options,
}
%}
{{ menuData | json_encode | raw }}